// frontend-react/src/components/ApplyForVisit.js
import {useState} from 'react';

const ApplyForVisit = () => {
    const [surname, setSurname] = useState('');
    const [name, setName] = useState('');
    const [patronymic, setPatronymic] = useState('');
    const [email, setEmail] = useState('');
    const [phone, setPhone] = useState('');
    const [visitPurpose, setVisitPurpose] = useState('');
    const [document, setDocument] = useState({type: 'passport', number: ''});
    const [consent, setConsent] = useState(false);
    const [message, setMessage] = useState({show: false, isError: false, text: ''});
    const [errors, setErrors] = useState({});
    const [isSubmitting, setIsSubmitting] = useState(false);

    const handleInputChange = (event) => {
        const {id, value} = event.target;
        switch (id) {
            case 'surname':
                setSurname(value);
                break;
            case 'name':
                setName(value);
                break;
            case 'patronymic':
                setPatronymic(value);
                break;
            case 'email':
                setEmail(value);
                break;
            case 'phone':
                setPhone(value);
                break;
            case 'doc_number':
                setDocument({...document, number: value});
                break;
            case 'visit_purpose':
                setVisitPurpose(value);
                break;
            case 'passport':
            case 'drivers_license':
                setDocument({...document, type: value});
                break;
            case 'data_processing_consent':
                setConsent(event.target.checked);
                break;
            default:
                break;
        }
    };

    const validate = () => {
        let formIsValid = true;
        let errors = {};
        if (!surname) {
            formIsValid = false;
            errors.surname = 'Поле обязательно для заполнения';
        }
        if (!name) {
            formIsValid = false;
            errors.name = 'Поле обязательно для заполнения';
        }
        if (!email) {
            formIsValid = false;
            errors.email = 'Поле обязательно для заполнения';
        }
        if (!phone) {
            formIsValid = false;
            errors.phone = 'Поле обязательно для заполнения';
        }
        if (!document.number) {
            formIsValid = false;
            errors.doc_number = 'Поле обязательно для заполнения';
        }
        if (!visitPurpose) {
            formIsValid = false;
            errors.visit_purpose = 'Поле обязательно для заполнения';
        }
        if (!consent) {
            formIsValid = false;
            errors.consent = 'Поле обязательно для заполнения';
        }
        setErrors(errors);
        return formIsValid;
    };

    const sendForm = () => {
        if (validate()) {
            // TODO: send form data to server
            setMessage({show: true, isError: false, text: 'Форма успешно отправлена'});
        } else {
            setMessage({show: true, isError: true, text: 'Пожалуйста, заполните все обязательные поля'});
        }
    };

    return (
        <div className="h-100 d-flex align-items-center justify-content-center mt-4">
            <div className="container w-auto">
                {message.show && (
                    <div className={`alert ${message.isError ? 'alert-danger' : 'alert-success'}`} role="alert">
                        {message.text}
                    </div>
                )}
                <h3 className="mb-5">Заявка на посещение</h3>
                <form>
                    <div className="row">
                        <div className="col-md-6">
                            <h5 className="text-muted">Контактная информация</h5>
                            <div className="form-group mb-3">
                                <label htmlFor="surname">Фамилия</label>
                                <input
                                    type="text"
                                    value={surname}
                                    onChange={(e) => setSurname(e.target.value)}
                                    className="form-control"
                                    id="surname"
                                    placeholder="Иванов"
                                />
                                <small id="surnameErrors" className="form-text text-danger">
                                    {errors.surname}
                                </small>
                            </div>
                            <div className="form-group mb-3">
                                <label htmlFor="name">Имя</label>
                                <input
                                    type="text"
                                    value={name}
                                    onChange={(e) => setName(e.target.value)}
                                    className="form-control"
                                    id="name"
                                    placeholder="Иван"
                                />
                                <small id="nameErrors" className="form-text text-danger">
                                    {errors.name}
                                </small>
                            </div>
                            <div className="form-group mb-3">
                                <label htmlFor="patronymic">Отчество</label>
                                <input
                                    type="text"
                                    value={patronymic}
                                    onChange={(e) => setPatronymic(e.target.value)}
                                    className="form-control"
                                    id="patronymic"
                                    placeholder="Иванович"
                                />
                                <small id="patronymicErrors" className="form-text text-danger">
                                    {errors.patronymic}
                                </small>
                            </div>
                            <div className="form-group mb-3">
                                <label htmlFor="email">E-mail</label>
                                <input
                                    type="email"
                                    value={email}
                                    onChange={(e) => setEmail(e.target.value)}
                                    className="form-control"
                                    id="email"
                                    placeholder="email@ilum.top"
                                />
                                <small id="emailErrors" className="form-text text-danger">
                                    {errors.email}
                                </small>
                            </div>
                            <div className="form-group mb-3">
                                <label htmlFor="phone">Телефон</label>
                                <input
                                    type="tel"
                                    value={phone}
                                    onChange={(e) => setPhone(e.target.value)}
                                    className="form-control"
                                    id="phone"
                                    placeholder="+71234567890"
                                />
                                <small id="phoneErrors" className="form-text text-danger">
                                    {errors.phone}
                                </small>
                            </div>
                        </div>
                        <div className="col-md-6">
                            <h5 className="text-muted">Документ, удостоверяющий личность</h5>
                            <span>Выберите тип документа</span>
                            <div className="row mb-3">
                                <div className=" form-group col-md-6">
                                    <input className="me-1" type="radio" name="doc_type" id="passport" value="passport"
                                           onChange={handleInputChange}/>
                                    <label htmlFor="passport">Паспорт</label>
                                </div>
                                <div className="form-group col-md-6">
                                    <input className="me-1" type="radio" name="doc_type" id="drivers_license"
                                           value="drivers_license" onChange={handleInputChange}/>
                                    <label htmlFor="drivers_license">Водительское удостоверение</label>
                                </div>
                            </div>
                            <div className="form-group mb-3">
                                <label htmlFor="doc_number">Номер документа</label>
                                <input
                                    type="text"
                                    value={document.number}
                                    onChange={(e) => setDocument({...document, number: e.target.value})}
                                    className="form-control"
                                    id="doc_number"
                                    placeholder="1234 567890"
                                />
                                <small id="doc_numberErrors" className="form-text text-danger">
                                    {errors.doc_number}
                                </small>
                            </div>
                            <div className="form-group mb-3">
                                <label htmlFor="visit_purpose">Цель посещения</label>
                                <input
                                    type="text"
                                    value={visitPurpose}
                                    onChange={(e) => setVisitPurpose(e.target.value)}
                                    className="form-control"
                                    id="visit_purpose"
                                />
                                <small id="visit_purposeErrors" className="form-text text-danger">
                                    {errors.visit_purpose}
                                </small>
                            </div>
                            <div className="form-group mb-3">
                                <input className="me-1" type="checkbox" name="consent" id="consent" value="consent"
                                       onChange={handleInputChange}/>
                                <label htmlFor="consent">Согласие на обработку персональных данных</label>
                                <small id="consentErrors" className="form-text text-danger">
                                    {errors.consent}
                                </small>
                            </div>
                        </div>
                    </div>
                    <button type="button" className="btn btn-primary" onClick={sendForm} disabled={isSubmitting}>
                        {isSubmitting ?
                            <span className="spinner-grow spinner-grow-sm" role="status" hidden="true"></span> +
                            'Отправка...' : 'Отправить'}
                    </button>
                </form>
            </div>
        </div>
    );
}

export default ApplyForVisit;

// frontend/src/components/ApplyForVisit.vue
<template>
  <div class="h-100 d-flex align-items-center justify-content-center">
    <div class="container w-auto">
      <div class="alert" :class="{ 'alert-danger': message.isError, 'alert-success': !message.isError }" role="alert"
           v-if="message.show">
        {{ message.text }}
      </div>
      <h3 class="mb-5">Заявка на посещение</h3>
      <form>
        <div class="row">
          <div class="col-md-6">
            <h5 class="text-muted">Контактная информация</h5>
            <div class="form-group mb-3">
              <label for="surname">Фамилия</label>
              <input type="text" v-model="surname" class="form-control" id="surname" placeholder="Иванов">
              <small id="surnameErrors" v-if="'surname' in errors" class="form-text text-danger">
                {{ errors.surname }}
              </small>
            </div>
            <div class="form-group mb-3">
              <label for="name">Имя</label>
              <input type="text" v-model="name" class="form-control" id="name" placeholder="Иван">
              <small id="nameErrors" v-if="'name' in errors" class="form-text text-danger">
                {{ errors.name }}
              </small>
            </div>
            <div class="form-group mb-3">
              <label for="patronymic">Отчество</label>
              <input type="text" v-model="patronymic" class="form-control" id="patronymic" placeholder="Иванович">
              <small id="patronymicErrors" v-if="'patronymic' in errors" class="form-text text-danger">
                {{ errors.patronymic }}
              </small>
            </div>
            <div class="form-group mb-3">
              <label for="email">E-mail</label>
              <input type="email" v-model="email" class="form-control" id="email" placeholder="email@ilum.top">
              <small id="emailErrors" v-if="'email' in errors" class="form-text text-danger">
                {{ errors.email }}
              </small>
            </div>
            <div class="form-group mb-3">
              <label for="phone">Телефон</label>
              <input type="tel" v-model="phone" class="form-control" id="phone" placeholder="+71234567890">
              <small id="phoneErrors" v-if="'phone' in errors" class="form-text text-danger">
                {{ errors.phone }}
              </small>
            </div>
          </div>
          <div class="col-md-6">
            <h5 class="text-muted">Информация о документе</h5>
            <span class="">Тип документа</span>
            <div class="row mb-3">
              <div class="form-group col-md-6">
                <input class="me-1" type="radio" id="passport" value="passport"
                       v-model="document.type" name="doc_type" checked/>
                <label for="passport">Паспорт</label>
              </div>
              <div class="form-group col-md-6">
                <input class="me-1" type="radio" id="drivers_license"
                       value="drivers_license" v-model="document.type" name="doc_type"/>
                <label for="drivers_license">Водительское удостоверение</label>
              </div>
            </div>
            <div class="form-group mb-3">
              <label for="doc_number">Номер документа</label>
              <input type="text" v-model="document.number" class="form-control" id="doc_number"
                     placeholder="1234 567890">
              <small id="doc_numberErrors" v-if="'doc_number' in errors" class="form-text text-danger">
                {{ errors.doc_number }}
              </small>
            </div>
            <div class="form-group mb-3">
              <label for="visit_purpose">Цель посещения</label>
              <input type="text" v-model="visitPurpose" class="form-control" id="visit_purpose"
                     placeholder="Получение документов">
              <small id="visit_purposeErrors" v-if="'visit_purpose' in errors" class="form-text text-danger">
                {{ errors.visit_purpose }}
              </small>
            </div>
          </div>
        </div>
        <div class="form-group mb-3">
          <div class="w-100">
            <input type="checkbox" class="me-1" v-model="consent" id="data_processing_consent"/>
            <label for="data_processing_consent">Даю согласие на <a href="#">обработку персональных данных</a></label>
          </div>
          <small id="consentErrors" v-if="'consent' in errors" class="form-text text-danger">
            {{ errors.consent }}
          </small>
        </div>
        <button @click="sendForm"
                class="btn btn-primary" type="button" :disabled="sending">
          <span v-if="sending"
                class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
          {{ sending ? 'Отправка...' : 'Отправить' }}
        </button>
      </form>
    </div>
  </div>
</template>

<script>
import api from "@/services/api";

export default {
  name: "ApplyForVisit",
  data() {
    return {
      name: "",
      surname: "",
      patronymic: "",
      email: "",
      phone: "",
      visitPurpose: "",
      document: {
        type: "passport",
        series: "",
        number: "",
      },
      consent: false,
      message: {
        show: false,
        text: "",
        isError: false,
      },
      errors: {},
      sending: false,
    };
  },
  methods: {
    checkForm: function (e) {
      if (!this.name) {
        this.errors.name = "Введите имя";
      }
      if (!this.surname) {
        this.errors.surname = "Введите фамилию";
      }
      if (!this.patronymic) {
        this.errors.patronymic = "Введите отчество";
      }
      if (!this.email) {
        this.errors.email = "Введите email";
      } else if (!this.validEmail(this.email)) {
        this.errors.email = "Введите корректный email";
      }
      if (!this.phone) {
        this.errors.phone = "Введите телефон";
      }
      if (!this.document.type || !this.document.number) {
        this.errors.doc_number = "Некорректный документ.";
      }
      if (!this.consent) {
        this.errors.consent = "Необходимо дать согласие на обработку персональных данных";
      }
      if (!Object.keys(this.errors).length) {
        return true;
      }
      e.preventDefault();
      return false;
    },
    validEmail: function (email) {
      // eslint-disable-next-line no-useless-escape
      const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
      return re.test(String(email).toLowerCase());
    },
    sendForm: function (e) {
      this.sending = true;
      this.errors = {};
      this.message.show = false;
      if (!this.checkForm(e)) {
        api.postApplication(
            {
              "name": this.name,
              "surname": this.surname,
              "patronymic": this.patronymic,
              "email": this.email,
              "phone": this.phone,
              "visitPurpose": this.visitPurpose,
              "document": this.document
            }
        ).then(() => {
          this.message.text = "Заявка успешно отправлена";
          this.message.isError = false;
        }).catch(() => {
          this.message.text = "Произошла ошибка. Пожалуйста, попробуйте позже.";
          this.message.isError = true;
        }).finally(() => {
          this.message.show = true;
          this.sending = false;
        });
      }
    }
  }
}
</script>

<style scoped>

</style>
