// frontend-react/src/components/LoginForm.js
import {useEffect, useState} from "react";
import {useNavigate} from "react-router-dom";
import {authStore} from "../store/auth";


const LoginForm = () => {
    const history = useNavigate();
    const [username, setUsername] = useState("");
    const [password, setPassword] = useState("");
    const [error, setError] = useState("");
    const [validationFailed, setValidationFailed] = useState([]);

    useEffect(() => {
        if (authStore.user) {
            history("/home");
        }
    }, [history]);

    function validateFields() {
        setValidationFailed([]);
        let successful = true;
        if (!username) {
            setValidationFailed((prev) => [...prev, "username"]);
            successful = false;
        }
        if (!password) {
            setValidationFailed((prev) => [...prev, "password"]);
            successful = false;
        }

        return successful;
    }

    async function login() {
        if (!validateFields()) {
            return;
        }
        try {
            await authStore.login({username, password})
            history("/home");
        } catch (e) {
            setError("Неверное имя пользователя или пароль");
            console.debug(authStore.user);
        }
    }

    const handleKeyDown = async (event) => {
        if (event.key === "Enter") {
            await login();
        }
    }

    return (
        <div className={"container flex mt-4"}>
        <main className="form-signin">
            <form onKeyDown={handleKeyDown}>
                <h1 className="h3 mb-3 fw-normal">Авторизация</h1>
                {error && (
                    <div className="alert alert-danger" role="alert">
                        {error}
                    </div>
                )}
                <div className={`form-floating`}>
                    <input
                        type="text"
                        className={`form-control ${validationFailed.includes("username") ? " is-invalid" : ""}`}
                        value={username}
                        id="usernameInput"
                        placeholder="user"
                        onChange={(event) => setUsername(event.target.value)}
                    />
                    <label htmlFor="usernameInput">Имя пользователя</label>
                    {validationFailed.includes("username") && (
                        <div className="invalid-feedback">Поле не может быть пустым</div>
                    )}
                </div>
                <div className={`form-floating${validationFailed.includes("password") ? " is-invalid" : ""}`}>
                    <input
                        type="password"
                        className={`form-control ${validationFailed.includes("password") ? " is-invalid" : ""}`}
                        value={password}
                        id="passwordInput"
                        placeholder="****"
                        onChange={(event) => setPassword(event.target.value)}
                    />
                    <label htmlFor="passwordInput">Пароль</label>
                    {validationFailed.includes("password") && (
                        <div className="invalid-feedback">Поле не может быть пустым</div>
                    )}
                </div>
                <div className="checkbox mb-3">
                    <label>
                        <input type="checkbox" value="remember-me"/> Запомнить меня
                    </label>
                </div>
                <button className="w-100 btn btn-lg btn-primary" onClick={login} type="button">
                    Вход
                </button>
            </form>
        </main>
        </div>
    );
}

export default LoginForm;

// frontend/src/components/LoginForm.vue
<template>
  <main class="form-signin">
    <form @keydown.enter="login">
      <h1 class="h3 mb-3 fw-normal">Авторизация</h1>
      <div class="alert alert-danger" v-if="error.length" role="alert">
        {{ error }}
      </div>
      <div class="form-floating">
        <input type="text" class="form-control" v-model="this.username" id="usernameInput" placeholder="user">
        <label for="usernameInput">Имя пользователя</label>
      </div>
      <div class="form-floating">
        <input type="password" required class="form-control" v-model="this.password" id="passwordInput" placeholder="****">
        <label for="passwordInput">Пароль</label>
      </div>

      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Запомнить меня
        </label>
      </div>
      <button class="w-100 btn btn-lg btn-primary" @click="login" type="button">Вход</button>
    </form>
  </main>
</template>

<script>
export default {
  name: "LoginForm",
  data() {
    return {
      username: "",
      password: "",
      error: "",
      validationFailed: [],
    };
  },
  methods: {
    validateFields() {
      this.validationFailed = [];
      if (!this.username) {
        this.validationFailed.push("username");
        return false;
      }
      if (!this.password) {
        this.validationFailed.push("password");
        return false;
      }
      return true;
    },
    login() {
      this.$store.dispatch("auth/login", {
        username: this.username,
        password: this.password,
      }).then(() => {
        console.log("success");
        this.$router.push({ name: "Home" });
      }).catch((error) => {
        // check for null error
        if (error.status === 401) {
          this.error = "Неверное имя пользователя или пароль";
        } else {
          this.error = "Неизвестная ошибка";
        }
      });
    },
  },
}
</script>

<style scoped>
html,
body {
  height: 100%;
}

body {
  display: flex;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}

.form-signin .checkbox {
  font-weight: 400;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

</style>
