// frontend-react/src/components/UsersList.js
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {apiService} from '../services/api';
import {faCoffee, faUserEdit, faUserMinus, faUserPlus} from "@fortawesome/free-solid-svg-icons";

const UsersList = () => {
    const history = useNavigate();
    const [users, setUsers] = useState([]);
    const [loading, setLoading] = useState(true);
    const [message, setMessage] = useState({ text: '', isError: false });

    const alertClass = message.isError ? 'alert-danger' : 'alert-success';

    useEffect(() => {
        const getUsers = async () => {
            try {
                const response = await apiService.getAdmins();
                setUsers(response.data);
            } catch (e) {
                setMessage({ text: 'Ошибка при получении списка пользователей', isError: true });
            } finally {
                setLoading(false);
            }
        };
        getUsers();
    }, []);

    const editUser = (id) => {
        history(`/users/${id}`);
    };

    const deleteUser = async (id) => {
        try {
            await apiService.deleteAdmin(id);
            setUsers(users.filter((user) => user.id !== id));
            setMessage({ text: 'Пользователь успешно удален', isError: false });
        } catch (e) {
            setMessage({ text: 'Ошибка при удалении пользователя', isError: true });
        }
    };

    return (
        <div className="container mt-4">
            <div className="row">
                <div className="col-md-12">
                    <h1>Список пользователей</h1>
                    {loading && (
                        <div className="d-flex justify-content-center w-100 mt-5 mb-5">
                            <div className="spinner-grow" role="status"></div>
                        </div>
                    )}
                    {message.text && (
                        <div className={`alert ${alertClass}`} role="alert">
                            {message.text}
                        </div>
                    )}
                    {!loading && (
                        <table className="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">Имя пользователя</th>
                                <th scope="col">Тип</th>
                                <th scope="col">Действия</th>
                            </tr>
                            </thead>
                            <tbody>
                            {users.map((user) => (
                                <tr key={user.id}>
                                    <td>{user.username}</td>
                                    <td>{user.admin_type === 'admin' ? 'Администратор' : 'Господь Бог'}</td>
                                    <td>
                                        <div className="btn-group" role="group">
                                            <button type="button" className="btn btn-primary" onClick={() => editUser(user.id)}>
                                                <FontAwesomeIcon icon={faUserEdit} />
                                            </button>
                                            <button type="button" className="btn btn-danger" onClick={() => deleteUser(user.id)}>
                                                <FontAwesomeIcon icon={faUserMinus} />
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                            </tbody>
                        </table>
                    )}
                    <button className="btn btn-primary" onClick={() => editUser(null)}>
                        <FontAwesomeIcon className={'me-2'} icon= {faUserPlus} />
                        Добавить пользователя
                    </button>
                </div>
            </div>
        </div>
    );
};

export default UsersList;

// frontend/src/components/UsersList.vue
<template>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Список пользователей</h1>
        <div v-if="loading" class="d-flex justify-content-center w-100 mt-5 mb-5">
          <div class="spinner-grow" role="status">
          </div>
        </div>
        <div v-if="message.text" class="alert" :class="alertClass" role="alert">
          {{ message.text }}
        </div>
        <table v-if="!loading" class="table table-striped">
          <thead>
          <tr>
            <th scope="col">Имя пользователя</th>
            <th scope="col">Тип</th>
            <th scope="col">Действия</th>
          </tr>
          </thead>
          <tbody>
          <tr v-for="user in users" :key="user.id">
            <td>{{ user.username }}</td>
            <td>{{user.admin_type === 'admin' ? 'Администратор' :
                    'Господь Бог'
              }}
            </td>
            <td>
              <div class="btn-group" role="group">
                <button type="button" class="btn btn-primary" @click="editUser(user.id)">
                  <font-awesome-icon icon="user-edit"/>
                </button>
                <button type="button" class="btn btn-danger" @click="deleteUser(user.id)">
                  <font-awesome-icon icon="user-minus"/>
                </button>
              </div>
            </td>
          </tr>
          </tbody>
        </table>
        <button @click="editUser(null)" class="btn btn-primary">
          <font-awesome-icon icon="plus"/>
          Добавить пользователя
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import api from "@/services/api";

export default {
  name: "UsersList",
  data() {
    return {
      users: [],
      loading: true,
      message: {
        text: "",
        isError: false,
      },
    }
  },
  computed: {
    alertClass() {
      return {
        "alert-danger": this.message.isError,
        "alert-success": !this.message.isError,
      }
    },
  },
  async mounted() {
    try {
      const response = await api.getAdmins();
      this.users = response.data;
      console.debug(this.users);
    } catch (e) {
      this.message.text = "Ошибка при получении списка пользователей";
      this.message.isError = true;
    } finally {
      this.loading = false;
    }
  },
  methods: {
    editUser(id) {
      this.$router.push({name: "SingleUser", params: {id: id}});
    },
    async deleteUser(id) {
      try {
        await api.deleteAdmin(id);
        this.users = this.users.filter(user => user.id !== id);
        this.message = {
          text: "Пользователь успешно удален",
          isError: false,
        };
      } catch (e) {
        this.message.text = "Ошибка при удалении пользователя";
        this.message.isError = true;
      }
    }
  }
}
</script>

<style scoped>

</style>
