// frontend/src/components/SingleUser.vue
<template>
  <div class="h-100 d-flex align-items-center justify-content-center">
    <div class="container w-auto">
      <h1>Пользователь</h1>
      <div v-if="message.text" class="alert" :class="alertClass" role="alert">
        {{ message.text }}
      </div>
      <form @submit.prevent="checkForm">
        <div class="form-group mb-3">
          <label for="name">Имя пользователя</label>
          <input
              type="text"
              class="form-control"
              id="name"
              placeholder="Имя"
              v-model="user.username"
          />
          <small class="form-text text-danger" v-if="'username' in errors">
            {{ errors.username }}
          </small>
        </div>
        <div class="form-group mb-3">
          <label for="password">Пароль</label>
          <input
              type="password"
              class="form-control"
              id="password"
              placeholder="Пароль"
              v-model="user.password"/>
        </div>
        <div class="form-group mb-3">
          <label for="password2">Повторите пароль</label>
          <input
              type="password"
              class="form-control"
              id="password2"
              placeholder="Повторите пароль"
              v-model="user.password2"/>
          <small class="form-text text-danger" v-if="'password' in errors">
            {{ errors.password }}
          </small>
        </div>
        <div class="form-group mb-3">
          <label for="adminType">Роль</label>
          <select
              class="form-select"
              id="adminType"
              v-model="user.admin_type">
            <option value="admin">Администратор</option>
            <option value="super_admin">Господь Бог</option>
          </select>
        </div>
        <button type="button" @click="sendForm" class="btn btn-primary">{{ newUser ? 'Добавить' : 'Сохранить' }}
        </button>
      </form>
    </div>
  </div>
</template>

<script>
import api from "@/services/api";

export default {
  name: "SingleUser",
  data() {
    return {
      newUser: !this.$route.params.id,
      user: {},
      loading: true,
      message: {
        type: "",
        text: "",
      },
      errors: {},
      alertClasses: {
        success: "alert-success",
        error: "alert-danger",
        info: "alert-info",
      },
    };
  },
  computed: {
    alertClass() {
      return this.alertClasses[this.message.type];
    },
  },
  async mounted() {
    try {
      if (this.newUser) {
        this.user.admin_type = "admin";
        return;
      }
      const response = await api.getAdmin(this.$route.params.id);
      this.user = response.data;
    } catch (e) {
      this.message = {
        type: "error",
        text: "Произошла ошибка при загрузке пользователя",
      };
      console.log(e);
    } finally {
      this.loading = false;
    }
  },
  methods: {
    async sendForm() {
      this.errors = {};
      if (!this.validateForm())
        return;
      try {
        if (this.newUser) {
          await api.addAdmin(this.user);
          this.message = {
            type: "success",
            text: "Пользователь успешно добавлен",
          };
        } else {
          await api.modifyAdmin(this.user);
          this.message = {
            type: "success",
            text: "Пользователь успешно изменен",
          };
        }
      } catch (e) {
        console.log(e);
        if (e.response && e.response.status === 409) {
          this.message = {
            type: "error",
            text: "Пользователь с таким именем уже существует",
          };
        } else {
          this.message = {
            type: "error",
            text: "Произошла ошибка при сохранении пользователя",
          };
        }
      }
    },
    validateForm() {
      this.errors = {};
      if (!this.user.username) {
        this.errors.username = "Поле обязательно";
      }
      if (this.newUser && !this.user.password) {
        this.errors.password = "Поле обязательно";
      }
      if (this.user.password !== this.user.password2) {
        this.errors.password = "Пароли не совпадают";
      }
      return Object.keys(this.errors).length === 0;
    },
  }
}
</script>

<style scoped>

</style>

// frontend-react/src/components/SingleUser.js
import React, {useState, useEffect} from "react";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {apiService} from "../services/api";
import {useParams} from "react-router-dom";

const SingleUser = () => {
    const props = useParams();
    const [newUser] = useState(!props.id);
    const [user, setUser] = useState({});
    const [loading, setLoading] = useState(true);
    const [message, setMessage] = useState({type: "", text: ""});
    const [errors, setErrors] = useState({});
    const alertClasses = {success: "alert-success", error: "alert-danger", info: "alert-info"};

    const validateForm = () => {
        setErrors({});
        if (!user.username) {
            setErrors((prevErrors) => ({...prevErrors, username: "Поле обязательно"}));
        }
        if (newUser && !user.password) {
            setErrors((prevErrors) => ({...prevErrors, password: "Поле обязательно"}));
        }
        if (user.password !== user.password2) {
            setErrors((prevErrors) => ({...prevErrors, password: "Пароли не совпадают"}));
        }
        return Object.keys(errors).length === 0;
    };

    const sendForm = async () => {
        setErrors({});
        if (!validateForm()) return;
        try {
            if (newUser) {
                await apiService.addAdmin(user);
                setMessage({type: "success", text: "Пользователь успешно добавлен"});
            } else {
                await apiService.modifyAdmin(user);
                setMessage({type: "success", text: "Пользователь успешно изменен"});
            }
        } catch (e) {
            console.log(e);
            if (e.response && e.response.status === 409) {
                setMessage({type: "error", text: "Пользователь с таким именем уже существует"});
            } else {
                setMessage({type: "error", text: "Произошла ошибка при сохранении пользователя"});
            }
        }
    };

    useEffect(() => {
        const fetchData = async () => {
            try {
                if (newUser) {
                    setUser((prevUser) => ({...prevUser, admin_type: "admin"}));
                    return;
                }
                const response = await apiService.getAdmin(props.id);
                setUser(response.data);
            } catch (e) {
                setMessage({type: "error", text: "Произошла ошибка при загрузке пользователя"});
                console.log(e);
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [props.id, newUser]);

    const alertClass = alertClasses[message.type];

    return (<div className="h-100 d-flex align-items-center justify-content-center">
            <div className="container w-auto">
                <h1>Пользователь</h1>
                {message.text && (<div className={`alert ${alertClass}`} role="alert">
                        {message.text}
                    </div>)}
                <form onSubmit={(e) => e.preventDefault()}>
                    <div className="form-group mb-3">
                        <label htmlFor="name">Имя пользователя</label>
                        <input
                            type="text"
                            className="form-control"
                            id="name"
                            placeholder="Имя"
                            value={user.username || ""}
                            onChange={(e) => setUser({...user, username: e.target.value})}
                        />
                        {errors.username && <small className="form-text text-danger">{errors.username}</small>}
                    </div>
                    <div className="form-group mb-3">
                        <label htmlFor="password">Пароль</label>
                        <input
                            type="password"
                            className="form-control"
                            id="password"
                            placeholder="Пароль"
                            value={user.password || ""}
                            onChange={(e) => setUser({...user, password: e.target.value})}
                        />
                        {errors.password && <small className="form-text text-danger">{errors.password}</small>}
                    </div>
                    <div className="form-group mb-3">
                        <label htmlFor="password2">Повторите пароль</label>
                        <input
                            type="password"
                            className="form-control"
                            id="password2"
                            placeholder="Повторите пароль"
                            value={user.password2 || ""}
                            onChange={(e) => setUser({...user, password2: e.target.value})}
                        />
                    </div>
                    <div className="form-group mb-3">
                        <label htmlFor="admin_type">Тип пользователя</label>
                        <select
                            className="form-control"
                            id="admin_type"
                            value={user.admin_type || ""}
                            onChange={(e) => setUser({...user, admin_type: e.target.value})}
                        >
                            <option value="admin">Администратор</option>
                            <option value="super_admin">Господь Бог</option>
                        </select>
                    </div>
                    <button type="submit" className="btn btn-primary" onClick={sendForm}>
                        {loading ? (<FontAwesomeIcon icon="spinner"
                                                     spin/>) : newUser ? ("Добавить") : ("Сохранить")}
                    </button>
                </form>
            </div>
        </div>);
};

export default SingleUser;
